### ISSUE TITLE
Add functions to read and write spin positions

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#318]
Since variable geometry has been introduced (in principle) with 2dea0ddfcd0e5fcabf805d79b3088fe073d8ada1, APIs shoud be added to
- save spin positions to a file
- save geometry information (basis, translations etc.) to a `.cfg` file
- read spin positions from a file (this would assume a single unit cell of corresponding size?)
- read geometry from a `.cfg` input file (basis, translations, etc.)

This API should become usable from the UI.

**Comment by GPMueller** [comment]
Implemented Core and API functions to write positions with 24125f1a0a9ae3da98c3d84fb5a5bc79a6561a19:

`Geometry_to_Config` for writing a geometry to `.cfg` is already implemented

**Comment by GPMueller** [comment]
The variable geometry API has been extended on `feature-refactor-geometry`, which was merged into `develop` with f36fea8e670a895ef55228c2818dc7822cbf2810.

**TODO:**
- [ ] Improve position file writing, adding necessary comment blocks specifying the lattice type, number of basis atoms and number of basis cells (comment block or something else?)
- [ ] API function for writing a "geometry info" file (should this be different from the input cfg parameters? Otherwise it is already implemented in `IO::Geometry_to_Config`)
- [ ] API function for reading spin positions from file
    - should it require an info block at the top of the data specifying number of basis cells etc?
    - should it assume one big basis cell?
    - should it assume an unchanged number of basis cells and simply overwrite the current data until NOS is reached?
    - should it just be handled exactly like the other vectorfield-file-formats?
- [ ] API function for reading "geometry info" file (simply our regular cfg?) and generating new geometry from it

**Probably this should be treated exactly like other vectorfield-files...**
